### PR TITLE
Added Test Cases

### PR DESCRIPTION
**Pull request by hemraj4545**
Added Test Cases for
- ``` TrailingZeros ```
- ``` OnesCount ```
- ``` RotateLeft ```

### CODE REVIEW

**Comment by lukechampine** [comment]
There are many, *many* things wrong here -- too many to list, frankly. I'll give you another chance to fix it, but after that I'm going to close this and let someone else try.

**Comment by hemraj4545** [comment]
@lukechampine okay will try to do that..

**Comment by hemraj4545** [comment]
Added ```TestLen``` #8 
Please verify and let me know if any changes needed. And suggest where I go wrong.

**Comment by lukechampine** [comment]
This still does not even compile. I'm going to assign the issue to someone else, sorry.

**Pull request closed without merging**
