### PR TITLE
Make hi/lo elements public

### PR DESCRIPTION
**Pull request by jwasinger**

### CODE REVIEW

**Comment by lukechampine** [comment]
Thanks for the PR!

I'm wondering whether these should be methods, or if the fields should just be exported. The latter seems a bit simpler to me. Thoughts?

**Comment by jwasinger** [comment]
> The latter seems a bit simpler to me.

Agreed.  I changed the PR accordingly.

**Comment by lukechampine** [comment]
perfect, thanks!

**Comment by jwasinger** [comment]
Thanks for the quick turnaround!

**Pull request merged**
